// Discussion questions (to open the floor after presenting) and related
// cross-reference verses (for further study) — keyed by verse id.

export const DISCUSSION_QUESTIONS = {
  "col3-23": ["What's one task this week you've been tempted to do half-heartedly?", "How would your work change if you pictured Christ as the one reviewing it?"],
  "prov16-3": ["What's a plan you're anxious about that you haven't actually prayed over yet?", "What does 'committing' a task to God look like in practice, not just in words?"],
  "phil4-13": ["Is there a place in your life right now where you need endurance more than victory?", "What's the difference between strength to achieve and strength to remain steady?"],
  "josh1-9": ["What's one situation this week that requires courage more than confidence?", "How does knowing God's presence change how you'd walk into a hard conversation?"],
  "ecc9-10": ["What's a task you've been tempted to phone in because it feels meaningless?", "Does knowing an outcome is uncertain change how hard you're willing to work?"],
  "gen2-2": ["Where in your week is rest not actually built in, just hoped for?", "What would it look like to treat rest as designed, not earned?"],
  "prov3-5": ["Where are you leaning hardest on your own understanding right now?", "What would it look like to hold a plan you're confident in more loosely?"],
  "gal6-9": ["What's something you've kept doing faithfully with no visible payoff yet?", "What tempts you to give up on good work before the harvest comes?"],
  "col3-17": ["What's a routine task today you usually do on autopilot?", "How would naming God's name over small tasks change your attitude toward them?"],
  "isa40-31": ["Does this season feel more like soaring, running, or just walking without fainting?", "What does 'waiting on the Lord' look like in the middle of a demanding week?"],
  "prov13-4": ["What's something you've wanted for a while but haven't acted on yet?", "What's the smallest next step you could take today?"],
  "eph4-32": ["Is there tension with a coworker that needs the first kindness from you?", "How does remembering your own forgiveness change how you extend it to others?"],
  "prov21-5": ["Where has hurry crept into decisions that deserve more thought?", "What's one decision today worth five more unhurried minutes?"],
  "matt6-33": ["What's currently at the very top of your priority list?", "What would it look like to put seeking God above that, practically?"],
  "1cor10-31": ["What's an ordinary task today that could be done 'to the glory of God'?", "Does glory require something dramatic, or can it show up in small consistency?"],
  "prov27-17": ["Who has sharpened you with honesty, even when it stung?", "Are you more often offering easy affirmation or honest sharpening to others?"],
  "phil2-3": ["When are you most tempted to push your own idea first in a meeting?", "What does esteeming someone 'better than yourself' look like without losing your own voice?"],
  "james1-2": ["What recurring frustration at work might be building patience in you?", "Can you name the trial and the training happening at the same time?"],
  "prov16-9": ["When has a plan you devised gotten rearranged by something unexpected?", "How do you usually respond when today's plan falls apart?"],
  "rom12-11": ["Do you unconsciously separate 'spiritual' life from 'work' life?", "What would fervency of spirit look like applied to your actual inbox today?"],
  "psalm90-17": ["What project needs you to pray for it to be established, not just finished?", "Why might Moses have repeated this request twice?"],
  "prov22-29": ["Do you work the same way whether or not you're being watched?", "What's a task today that no one will check on, but deserves your best anyway?"],
  "heb13-16": ["What's one practical way you could 'do good and communicate' this week?", "Why might ordinary generosity count as a sacrifice God is pleased with?"],
  "prov15-22": ["Is there a decision you're about to make in isolation that deserves outside input?", "Who's one person whose perspective you tend to skip asking for?"],
  "matt5-16": ["What conduct today is the clearest sermon your coworkers will actually see?", "Where are you tempted to let frustration outshine your good works?"],
  "prov12-24": ["Where has a slack hand crept into your routine lately?", "What would one deliberate act of diligence look like today?"],
  "1thess5-16": ["What's one specific thing you could give thanks for today, not just generally?", "How does continual prayer make ongoing gratitude more realistic?"],
  "prov11-25": ["What's one thing you could give away this week without keeping score?", "Have you ever experienced generosity coming back to you unexpectedly?"],
  "psalm118-24": ["Can you choose gladness about today before knowing how it goes?", "What's making it hard to feel glad about this particular Monday?"],
  "prov10-4": ["Where have you been coasting that's quietly costing you more than you realize?", "What's one deliberate act of diligence you could choose today?"],
  "col3-12": ["Which quality from this list — mercy, kindness, humility, patience — do you most need to 'put on' today?", "Do you tend to wait to feel ready before acting with character?"],
  "prov19-21": ["Which of your plans are you holding too tightly right now?", "How do you usually respond when your devices get overridden?"],
  "matt11-28": ["What are you carrying into this week that isn't even task-related?", "What would it mean to bring that honestly to Christ before naming your to-do list?"],
  "prov3-9": ["What would it look like to give God the firstfruits of your effort, not the leftovers?", "Where are you currently giving from the leftover margin instead of first?"],
  "james1-19": ["In your last disagreement, were you listening or preparing your response?", "What would slower speech and quicker listening change in your next hard conversation?"],
  "prov24-27": ["Is there a foundational task you've been skipping to get to the visible parts of a project?", "What's the 'field work' everything else in your week depends on?"],
  "psalm127-1": ["Are you asking God to bless your plans, or to build them with you from the start?", "What's the biggest project this week you haven't actually prayed over yet?"],
  "gal6-2": ["Who's someone whose burden you've noticed but haven't asked about?", "What's one real question you could ask a coworker today, and actually listen to?"],
  "prov4-23": ["What's actually been shaping your heart lately — anxiety, comparison, gratitude?", "What would it look like to guard your heart with the same diligence as a deadline?"],
  "isa41-10": ["Which of the four promises here — presence, strength, help, upholding — do you need most this week?", "What's making you anxious enough right now that it's worth naming honestly?"],
};

export const RELATED_VERSES = {
  "col3-23": ["Ephesians 6:7", "1 Corinthians 15:58"],
  "prov16-3": ["Psalm 37:5", "Proverbs 16:9"],
  "phil4-13": ["2 Corinthians 12:9", "Isaiah 40:29"],
  "josh1-9": ["Deuteronomy 31:6", "Isaiah 41:10"],
  "ecc9-10": ["Colossians 3:23", "Proverbs 22:29"],
  "gen2-2": ["Exodus 20:8-11", "Matthew 11:28"],
  "prov3-5": ["Psalm 37:5", "Proverbs 16:9"],
  "gal6-9": ["2 Thessalonians 3:13", "1 Corinthians 15:58"],
  "col3-17": ["1 Corinthians 10:31", "Colossians 3:23"],
  "isa40-31": ["Psalm 27:14", "2 Corinthians 4:16"],
  "prov13-4": ["Proverbs 10:4", "Proverbs 12:24"],
  "eph4-32": ["Colossians 3:13", "Matthew 6:14-15"],
  "prov21-5": ["Proverbs 19:2", "Proverbs 14:29"],
  "matt6-33": ["Psalm 37:4", "Matthew 6:25-34"],
  "1cor10-31": ["Colossians 3:17", "Colossians 3:23"],
  "prov27-17": ["Proverbs 27:6", "Ecclesiastes 4:9-10"],
  "phil2-3": ["Romans 12:10", "1 Peter 5:5"],
  "james1-2": ["Romans 5:3-4", "1 Peter 1:6-7"],
  "prov16-9": ["Proverbs 19:21", "Jeremiah 10:23"],
  "rom12-11": ["Ecclesiastes 9:10", "Colossians 3:23"],
  "psalm90-17": ["Psalm 90:12", "Psalm 127:1"],
  "prov22-29": ["Ecclesiastes 9:10", "Colossians 3:23"],
  "heb13-16": ["Galatians 6:10", "Proverbs 11:25"],
  "prov15-22": ["Proverbs 11:14", "Proverbs 24:6"],
  "matt5-16": ["1 Peter 2:12", "Philippians 2:15"],
  "prov12-24": ["Proverbs 10:4", "Proverbs 13:4"],
  "1thess5-16": ["Philippians 4:6", "Ephesians 6:18"],
  "prov11-25": ["2 Corinthians 9:6", "Luke 6:38"],
  "psalm118-24": ["Lamentations 3:22-23", "Psalm 118:1"],
  "prov10-4": ["Proverbs 13:4", "Proverbs 12:24"],
  "col3-12": ["Galatians 5:22-23", "Ephesians 4:2"],
  "prov19-21": ["Proverbs 16:9", "James 4:13-15"],
  "matt11-28": ["Psalm 55:22", "1 Peter 5:7"],
  "prov3-9": ["2 Corinthians 9:7", "Malachi 3:10"],
  "james1-19": ["Proverbs 15:1", "Ephesians 4:26"],
  "prov24-27": ["Luke 14:28", "Proverbs 21:5"],
  "psalm127-1": ["Proverbs 16:3", "Psalm 90:17"],
  "gal6-2": ["Romans 15:1", "1 Thessalonians 5:14"],
  "prov4-23": ["Philippians 4:7", "Proverbs 27:19"],
  "isa41-10": ["Deuteronomy 31:6", "Joshua 1:9"],
};
